Milestone 2 : React Calculater
RailonA/React-Project-Calculator pull request #2
Opened 2021-08-05 22:26 UTC by RailonA

Implement 4 components: 

- App
- Display
- Button Panel
- Button

2021-08-06 17:28 UTC, whiz25 requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work in this milestone. I have come a long way. Well done.
### Changes 🔕 🔕 🔕 
- add `.vscode` folder to `.gitignore` file. This folder contains sensitive information about your project. It may not be a good idea to commit it.
- check comments for suggestions.


### Martin Afani
#### Slack: whiz25

2021-08-06 17:28 UTC, whiz25 commented on src/components/app.js
> +/* eslint-disable func-style */
Fix this linter error. Disabling the linter rules changes the linter config which is used by all Microverse students.

2021-08-06 17:28 UTC, whiz25 commented on src/components/app.js
> +        <div>
Use React.Fragment shorthand syntax
```
<>...</>
```

2021-08-06 17:28 UTC, whiz25 commented on src/components/display.js
> +/* eslint-disable func-style */
Fix these linter errors

2021-08-06 17:28 UTC, whiz25 commented on src/components/button.js
> +/* eslint-disable func-style */
Fix the linter error instead of disabling the rule.

2021-08-06 17:28 UTC, whiz25 commented on src/components/buttonPanel.js
> +/* eslint-disable max-lines-per-function */
Fix the linter errors

2021-08-09 14:45 UTC, bellom approved these changes
## Hi @RailonA  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best**

2021-08-09 14:46 UTC, merged